### ISSUE TITLE
exception bug: dodgy URL

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#126]
go to http://speechbubble.org.uk/products/iphone-5/5s
and it causes a nice exception.

```
TypeError: Cannot call method 'toObject' of null
    at Promise.<anonymous> (/srv/speechbubble/server/api/product/product.controller.js:321:44)
    at Promise.<anonymous> (/srv/speechbubble/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/srv/speechbubble/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/srv/speechbubble/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/srv/speechbubble/node_modules/mongoose/lib/promise.js:114:23)
    at /srv/speechbubble/node_modules/mongoose/lib/model.js:2051:23
    at process._tickDomainCallback (node.js:492:13)
```

**Comment by raygerrard** [comment]
fixed in c4b9165a6aa9f81d8b1f1f8f6044a78563e297f5 

this requires re-save on any products that contain a / in the name field
